import Head from "next/head";
import Header from "../components/Header";
import NavBar from "../components/NavBar";
import styled from "styled-components";
import { useState } from "react";
import PlusButton from "../components/Buttons/PlusButton";
import CreateToDo from "../components/CreateToDo";
import InputFormHome from "../components/InputFormHome";

export default function Home({ addNewData, formData, addNewToDos, toDos }) {
  const [showMe, setShowMe] = useState(true);
  function toggle() {
    setShowMe(!showMe);
  }

  return (
    <>
      <Head>
        <title>Do I? I Do!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainWrapper>
        <TextWrapperStyle>
          <BigLineStyleA className="BigFontStyle">
            {formData === null ? (
              <p>Ihr Name & Sein Name </p>
            ) : (
              <p>
                {formData.brideName} & {formData.groomName}
              </p>
            )}
          </BigLineStyleA>
          <Line></Line>
          <MediumLineStyle className="MediumFontStyle2">
            {formData === null ? <p>XX.XX.XXXX</p> : <p>{formData.date}</p>}
            {formData === null ? (
              <p>Ort, Beginn</p>
            ) : (
              <p>
                {formData.place}, {formData.time}
              </p>
            )}
            <PlusButton toggle={toggle} />
          </MediumLineStyle>
          <InputFormHome
            showMe={showMe}
            setShowMe={setShowMe}
            addNewData={addNewData}
          />
          <BigLineStyleB className="BigFontStyle">
            <p>Eure wichtigsten To-Do´s</p>
          </BigLineStyleB>
          <Line></Line>
          <p className="MediumFontStyle">Fügt hier welche hinzu!</p>
          <CreateToDo addNewToDos={addNewToDos} toDos={toDos} />
        </TextWrapperStyle>
      </MainWrapper>
      <NavBar />
    </>
  );
}

const MainWrapper = styled.main`
  margin: 0;
  margin-bottom: 6rem;
  padding: 1rem;
`;

const TextWrapperStyle = styled.div`
  text-align: center;
`;

const BigLineStyleA = styled.div`
  margin-top: 3.5em;
`;

const BigLineStyleB = styled.div`
  margin-top: 3rem;
`;

export const Line = styled.p`
  color: #f5b424;
  border-bottom: 2px solid;
  width: 80%;
  margin: auto;
  margin-bottom: 1.5rem;
  margin-top: 0.5rem;
`;

const MediumLineStyle = styled.div`
  margin-bottom: 0.5rem;
`;
